"""initial schema with locations and roles

Revision ID: a25937d4f1c6
Revises: 
Create Date: 2026-08-21 05:03:59.380155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a25937d4f1c6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('details', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('criminals',
    sa.Column('criminalId', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('criminalHistory', sa.String(), nullable=True),
    sa.Column('riskScore', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('criminalId')
    )
    op.create_table('locations',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('roles',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('victims',
    sa.Column('victimId', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('victimId')
    )
    op.create_table('cases',
    sa.Column('firNumber', sa.String(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('crimeType', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('investigatingOfficer', sa.String(), nullable=True),
    sa.Column('district', sa.String(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('victimId', sa.String(), nullable=True),
    sa.Column('criminalIds', sa.JSON(), nullable=True),
    sa.Column('riskScore', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['district'], ['locations.name'], ),
    sa.ForeignKeyConstraint(['victimId'], ['victims.victimId'], ),
    sa.PrimaryKeyConstraint('firNumber')
    )
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('designation', sa.String(), nullable=True),
    sa.Column('badgeId', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('officeLocation', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('lastLogin', sa.String(), nullable=True),
    sa.Column('notificationsEnabled', sa.Boolean(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('twoFactorEnabled', sa.Boolean(), nullable=True),
    sa.Column('loginNotificationsEnabled', sa.Boolean(), nullable=True),
    sa.Column('passwordLastChanged', sa.String(), nullable=True),
    sa.Column('accountStatus', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['role'], ['roles.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('evidence',
    sa.Column('evidenceId', sa.String(), nullable=False),
    sa.Column('firNumber', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('fileName', sa.String(), nullable=True),
    sa.Column('fileSize', sa.String(), nullable=True),
    sa.Column('dateUploaded', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['firNumber'], ['cases.firNumber'], ),
    sa.PrimaryKeyConstraint('evidenceId')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('evidence')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_table('cases')
    op.drop_table('victims')
    op.drop_table('roles')
    op.drop_table('locations')
    op.drop_table('criminals')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
